add_subdirectory(builtin-01-math)
add_subdirectory(builtin-02-print)
add_subdirectory(builtin-03-ieee)
add_subdirectory(builtin-04-real-precision)
add_subdirectory(loop-01-index)
add_subdirectory(loop-02-ptr)
add_subdirectory(loop-03-pass-dims)
add_subdirectory(loop-04-multiple-parallel)
add_subdirectory(mapper-01-inter-module)
add_subdirectory(mapper-02-basetype)
add_subdirectory(mapper-03-variants)
add_subdirectory(mapper-04-dictfields)
add_subdirectory(mapper-05-alloc-field)
add_subdirectory(mapper-06-nested)
add_subdirectory(module-01-buf)
add_subdirectory(module-02-ptr-bigbuf)
add_subdirectory(type-01-procedures)
add_subdirectory(type-02-generics)
add_subdirectory(type-03-basefunc)

add_subdirectory(mglet-amdflang)
add_subdirectory(mglet-mockup)
